CREATE TABLE task_folders (
_id INTEGER PRIMARY KEY ,
online_id TEXT UNIQUE ,
local_id TEXT UNIQUE ,
change_key TEXT ,
is_default INTEGER DEFAULT(0) ,
deleted INTEGER DEFAULT(0) ,
delta_link TEXT ,
group_local_id TEXT ,
group_local_id_changed INTEGER DEFAULT(0) ,
delete_after_sync INTEGER DEFAULT(0) ,
name TEXT ,
name_changed INTEGER DEFAULT(0) ,
position TEXT DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%S', 'now')) ,
position_changed INTEGER DEFAULT(0) ,
show_completed_tasks INTEGER DEFAULT(1) ,
show_completed_tasks_changed INTEGER DEFAULT(0) ,
sorting_order TEXT DEFAULT('STORED_POSITION') ,
sorting_order_changed INTEGER DEFAULT(0) ,
sorting_direction TEXT DEFAULT('DESCENDING') ,
sorting_direction_changed INTEGER DEFAULT(0) ,
theme_background TEXT DEFAULT('mountain') ,
theme_background_changed INTEGER DEFAULT(0) ,
theme_color TEXT DEFAULT('dark_blue') ,
theme_color_changed INTEGER DEFAULT(0) ,
is_owner INTEGER DEFAULT(1) ,
sync_update_required INTEGER DEFAULT(0) ,
sharing_link TEXT ,
is_folder_shared INTEGER DEFAULT(0) ,
folder_type TEXT ,
sync_status TEXT DEFAULT('Synced') ,
sharing_status TEXT DEFAULT('NotShared') ,
sharing_status_changed INTEGER DEFAULT(0) ,
is_cross_tenant  INTEGER DEFAULT(0)
)